### ISSUE TITLE
Kernel repo reference broken for Lineage 20

### ISSUE THREAD

**Issue by sstefan** [samsungexynos7420/local_manifests#3]
For the Lineage 20.0 version, the repo reference to the kernel in 
https://github.com/samsungexynos7420/local_manifests/blame/5bece1f593628533b21cf74a6e7082ab873ecf55/universal7420.xml#L10
is pointing to a currently non-existing branch "lineage-20-bpf".

**Comment by fakemanoan** [comment]
this should be resolved now

**Comment by sstefan** [comment]
Thanks, but it's still not working for me, unfortunately. Trying to build 20.0 for zeroflte or zerolte here. 
After the recent commit 09cf700d7a8b7e34ca7c25df4c81f4097832cac7, I still get repo sync errors, apparently due to incorrect references:
```
(pmb) jenkins@75bfe6d9c79b:~/android/lineage$ repo sync -j1 --fail-fast
fatal: couldn't find remote ref refs/heads/lineage-20.0-unify

samsungexynos7420/android_hardware_samsung_slsi-linaro_codec2:
fatal: couldn't find remote ref refs/heads/lineage-20.0-unify
samsungexynos7420/android_hardware_samsung_slsi-linaro_codec2: sleeping 4.0 seconds before retrying
fatal: couldn't find remote ref refs/heads/lineage-20.0-unify
Syncing:  66% (840/1257), done in 1m19.701s
================================================================================
Repo command failed due to the following `SyncFailFastError` errors:
GitCommandError: 'fetch --quiet --progress github --prune --recurse-submodules=no --tags +refs/heads/lineage-20.0-unify:refs/remotes/github/lineage-20.0-unify +refs/tags/*:refs/tags/*' on samsungexynos7420/android_hardware_samsung_slsi-linaro_codec2 failed
stdout: fatal: couldn't find remote ref refs/heads/lineage-20.0-unify
```

Looks like some of the references should still point to other branches than "lineage-20.0-unify", or (if they exist) these need to be pushed to github. Could you please have another look at it?  Thank you!

**Comment by fakemanoan** [comment]
woops, forgot to make the branches public.

now it should be resolved.

**Comment by sstefan** [comment]
Thank you, that helped. Almost:
I was able to sync now after patching local_manifests/universal7420.xml aka roomservice.xml as
```
diff local_manifests/universal7420.xml ~/android/lineage/.repo/local_manifests/roomservice.xml 
7c7
<     <project path="device/samsung/zerolte" name="samsungexynos7420/android_device_samsung_zerolte" remote="github" revision="lineage-20.0-unify"/>
---
>     <project path="device/samsung/zerolte" name="samsungexynos7420/android_device_samsung_zerolte" remote="github" revision="lineage-20-unify"/>
12c12
<     <project path="kernel/samsung/universal7420" name="samsungexynos7420/android_kernel_samsung_universal7420" remote="github" revision="lineage-20-unify-clang-2" />
---
>     <project path="kernel/samsung/universal7420" name="samsungexynos7420/android_kernel_samsung_universal7420" remote="github" revision="lineage-20.0-unify-clang-2" />
```
Could you please quickly check the branch names again, if they really correspond to your recent builds for zeroflte/zerolte? I'd really appreciate being able reproduce these and then possibly help to work on some open issues.

**Comment by fakemanoan** [comment]
A typo in the kernel revision, and pushing an older zerolte branch to github.

Updated roomservice to be lineage-20.0-unify-clang-2, and pushed out lineage-20.0-unify to zerolte.

These branches are technically newer compared to my last build of lineageos 20, but they work and I plan to release new builds shortly using them. Main change was to support building the kernel with clang instead of gcc. Everything else should be ok. 

If you have any problems just let me know.

**Comment by sstefan** [comment]
The build worked well this time. Thank you!
